Overfitting Example
CertifaiAI/TrainingLabs pull request #144
Opened 2020-12-16 04:36 UTC by jacklynlxq

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Tested on 
- [ /] Windows  
- [ ] Linux Ubuntu  
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

Assign a reviewer to review your code.

2020-12-17 06:10 UTC, KianYang-Lee requested changes
Please perform the necessaries TQ

2020-12-17 06:10 UTC, KianYang-Lee commented on dl4j-labs/src/main/java/ai/certifai/training/classification/OverfittingGermanCreditClassification.java
> +//        EarlyStoppingConfiguration esConfig = new EarlyStoppingConfiguration.Builder()
Might not be necessary to include this in training file so as to train participants to code this out.

2020-12-17 06:10 UTC, KianYang-Lee commented on dl4j-labs/src/main/java/ai/certifai/training/classification/OverfittingGermanCreditClassification.java
> +//    private static int batchSize = 128; // batch size
You might want to exclude this line since you are not using it anyway

2020-12-17 07:03 UTC, KianYang-Lee reviewed
Looks good! @kenghooi-teoh I think we can proceed with merging.

2020-12-17 07:03 UTC, KianYang-Lee approved these changes

2020-12-17 09:05 UTC, jacklynlxq commented
Actually after some thoughts I've decided to work on visualising it on a graph, gonna push it soon, so sorry for the delay!

2021-01-07 02:19 UTC, jacklynlxq commented
@kenghooi-teoh tested and updated the script

2021-01-07 07:27 UTC, merged